name: ILoreEdit
main: cn.suml.iloreedit.ILoreEdit
version: 2.7.1
api-version: 1.13
author: myunco
website: https://github.com/myunco/ILoreEdit
description: 一款可以编辑物品名称和Lore的插件。
softdepend:
  - ProtocolLib
  - PlaceholderAPI
  - FoliaCompatibleAPI
folia-supported: true
commands:
  ILoreEdit:
    aliases: [ile, le]
    permission: iloreedit.admin
    permission-message: "§cYou don't have permission!"
  EditLore:
    aliases: [elore, lore, ll, el]
    permission: iloreedit.use
    permission-message: "§cYou don't have permission!"
permissions:
  iloreedit.admin:
    default: op
  iloreedit.use:
    default: op
