name: ILoreEdit
main: xyz.myunco.iloreedit.ILoreEdit
version: 2.0.2
api-version: 1.13
author: unco_
depend: [ProtocolLib]
commands:
  EditLore:
    aliases: [elore, lore, ll, el]
    permission: ILoreEdit.use
    permission-message: "§cYou don't have permission!"
  ILoreEdit:
    aliases: [ile, le]
    permission: ILoreEdit.use
    permission-message: "§cYou don't have permission!"
permissions:
  ILoreEdit.use:
    default: op