name: ILoreEdit
main: xyz.myunco.iloreedit.ILoreEdit
version: 2.0.0
api-version: 1.13
author: unco_
depend: [ProtocolLib]
commands:
  iItem:
    description: 'This is the main command of the plugin.'
    aliases: ['it', 'll', 'ii', 'lore']
    permission: ILoreEdit.use
    permission-message: "§cYou don't have permission!"
  ILoreEdit:
    description: 'This is the basic command of the plugin.'
    aliases: ['ile', 'le']
    permission: ILoreEdit.use
    permission-message: "§cYou don't have permission!"
permissions:
  ILoreEdit.use:
    default: op